return {
	{
		"folke/which-key.nvim",
		event = "VeryLazy",
		opts = {},
		config = function(_, opts)
			local wk = require("which-key")
			wk.setup(opts)
			wk.add({
				{ "<leader>f", group = "File" },
				{ "<leader>fb", desc = "Find Buffers" },
				{ "<leader>ff", desc = "Find File" },
				{ "<leader>fg", desc = "Find Grep" },
				{ "<leader>fp", desc = "Find File (all)" },
				{ "<leader>fr", desc = "Find Repo" },
				{ "<leader>fs", desc = "Find Symbols" },
				{ "<leader>fh", desc = "Find Help" },
				{ "<leader>g", group = "Git" },
				{ "<leader>gb", desc = "Blame Line" },
				{ "<leader>gp", desc = "Preview Hunk" },
				{ "<leader>gr", desc = "Reset Hunk" },
				{ "<leader>p", group = "Paste" },
				{ "<leader>ps", desc = "Paste Saving" },
				{ "<leader>r", group = "Run" },
				{ "<leader>rr", desc = "Run Code" },
				{ "<leader>rf", desc = "Run File" },
				{ "<leader>rp", desc = "Run Project" },
				{ "<leader>rc", desc = "Run Close" },
				{ "<leader>s", desc = "Replace Word" },
				{ "<leader>t", group = "Tree" },
				{ "<leader>tt", desc = "Open Neo-tree" },
				{ "<leader>tc", desc = "Close Neo-tree" },
				{ "<leader>v", group = "LSP" },
				{ "<leader>vc", group = "Code" },
				{ "<leader>vca", desc = "Code Action" },
				{ "<leader>vd", desc = "Show Diagnostics" },
				{ "<leader>vr", group = "References" },
				{ "<leader>vrn", desc = "Rename" },
				{ "<leader>vrr", desc = "Find References" },
				{ "<leader>vw", group = "Workspace" },
				{ "<leader>vws", desc = "Workspace Symbols" },
				{ "<leader>d", group = "Debug" },
			{ "<leader>db", desc = "Toggle Breakpoint" },
			{ "<leader>dc", desc = "Continue" },
			{ "<leader>di", desc = "Step Into" },
			{ "<leader>do", desc = "Step Over" },
			{ "<leader>dO", desc = "Step Out" },
			{ "<leader>dr", desc = "Open REPL" },
			{ "<leader>dq", desc = "Terminate" },
			{ "<leader>du", desc = "Toggle UI" },
			{ "<leader>x", group = "Diagnostics" },
				{ "<leader>xx", desc = "Diagnostics (Trouble)" },
				{ "<leader>xb", desc = "Buffer Diagnostics" },
				{ "<leader>xs", desc = "Symbols" },
			})
		end,
	},
}
